<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="2.0" xml:id="id_1" xmlns:ns2="http://xmlns.oracle.com/cloud/generic/rest/fault/REST/Get-Users" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:nstrgmpr="http://xmlns.oracle.com/cloud/adapter/REST/Get_Users_REQUEST/types" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:ns1="http://xmlns.oracle.com/cloud/adapter/REST/Get_Users_REQUEST" xmlns:nstrgdfl="http://xmlns.oracle.com/cloud/adapter/REST/Get-Users/types" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" oraext xsd xp20 ora oracle-xsl-mapper xsi fn xsl ignore01 nsmpr2 nsmpr3" xmlns:ignore01="http://www.oracle.com/XSL/Transform/java" ignore01:ignorexmlids="true" xmlns:nsmpr0="http://xmlns.oracle.com/cloud/adapter/REST/Get_First_Role_REQUEST/types" xmlns:nsmpr1="http://xmlns.oracle.com/cloud/adapter/REST/Get_Second_Role_REQUEST/types" xmlns:xml="http://www.w3.org/XML/1998/namespace" xmlns:nsmpr2="http://xmlns.oracle.com/cloud/adapter/REST/Get-First-Role/types" xmlns:nsmpr3="http://xmlns.oracle.com/cloud/adapter/REST/Get-Second-Role/types">
	<oracle-xsl-mapper:schema xml:id="id_2">
		<!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
		<oracle-xsl-mapper:mapSources xml:id="id_3">
			<oracle-xsl-mapper:source type="WSDL" xml:id="id_4">
				<oracle-xsl-mapper:schema location="../../application_8/outbound_9/resourcegroup_10/Get_Users_REQUEST.wsdl" xml:id="id_5"/>
				<oracle-xsl-mapper:rootElement name="execute" namespace="http://xmlns.oracle.com/cloud/adapter/REST/Get_Users_REQUEST/types" xml:id="id_6"/>
			</oracle-xsl-mapper:source>
			<oracle-xsl-mapper:source type="WSDL" xml:id="id_34">
				<oracle-xsl-mapper:schema location="../../application_41/inbound_42/resourcegroup_43/Get_Second_Role_REQUEST.wsdl" xml:id="id_35"/>
				<oracle-xsl-mapper:rootElement name="executeResponse" namespace="http://xmlns.oracle.com/cloud/adapter/REST/Get_Second_Role_REQUEST/types" xml:id="id_36"/>
				<oracle-xsl-mapper:param name="Get-Second-Role" xml:id="id_37"/>
			</oracle-xsl-mapper:source>
			<oracle-xsl-mapper:source type="WSDL" xml:id="id_39">
				<oracle-xsl-mapper:schema location="../../application_24/inbound_25/resourcegroup_26/Get_First_Role_REQUEST.wsdl" xml:id="id_40"/>
				<oracle-xsl-mapper:rootElement name="executeResponse" namespace="http://xmlns.oracle.com/cloud/adapter/REST/Get_First_Role_REQUEST/types" xml:id="id_41"/>
				<oracle-xsl-mapper:param name="Get-First-Role" xml:id="id_42"/>
			</oracle-xsl-mapper:source>
		</oracle-xsl-mapper:mapSources>
		<oracle-xsl-mapper:mapTargets xml:id="id_7">
			<oracle-xsl-mapper:target type="WSDL" xml:id="id_8">
				<oracle-xsl-mapper:schema location="../../application_8/outbound_9/resourcegroup_10/Get_Users_REQUEST.wsdl" xml:id="id_9"/>
				<oracle-xsl-mapper:rootElement name="executeResponse" namespace="http://xmlns.oracle.com/cloud/adapter/REST/Get_Users_REQUEST/types" xml:id="id_10"/>
			</oracle-xsl-mapper:target>
		</oracle-xsl-mapper:mapTargets>
		<!--GENERATED BY ORACLE XSL MAPPER 12.1.2.0.0-->
	</oracle-xsl-mapper:schema>
	<!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
	<xsl:param name="Get-Second-Role" xml:id="id_38"/>
	<xsl:param name="Get-First-Role" xml:id="id_43"/>
	<xsl:template match="/" xml:id="id_11">
		<nstrgmpr:executeResponse xml:id="id_12">
			<nstrgdfl:response-wrapper xml:id="id_26">
				<nstrgdfl:items xml:id="id_27">
					<xsl:for-each select="$Get-Second-Role/nsmpr1:executeResponse/nsmpr3:response-wrapper/nsmpr3:items[count(.|$Get-First-Role/nsmpr0:executeResponse/nsmpr2:response-wrapper/nsmpr2:items)=count($Get-First-Role/nsmpr0:executeResponse/nsmpr2:response-wrapper/nsmpr2:items)]" xml:id="id_28"/>
					<nstrgdfl:id xml:id="id_47">
						<xsl:value-of select="oraext:create-delimited-string($Get-First-Role/nsmpr0:executeResponse/nsmpr2:response-wrapper/nsmpr2:items/nsmpr2:id[. = $Get-Second-Role/nsmpr1:executeResponse/nsmpr3:response-wrapper/nsmpr3:items/nsmpr3:id], &quot;,&quot;)" xml:id="id_52"/>
					</nstrgdfl:id>
				</nstrgdfl:items>
			</nstrgdfl:response-wrapper>
		</nstrgmpr:executeResponse>
	</xsl:template>
</xsl:stylesheet>