<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="2.0" xml:id="id_1" xmlns:nstrgdfl="http://xmlns.oracle.com/cloud/generic/rest/fault/REST/Get-First-Role" xmlns:ns2="http://xmlns.oracle.com/cloud/generic/rest/fault/REST/Get-Users" xmlns:ns1="http://xmlns.oracle.com/cloud/adapter/REST/Get_First_Role_REQUEST" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:nssrcmpr="http://xmlns.oracle.com/cloud/adapter/REST/Get_Users_REQUEST/types" xmlns:nstrgmpr="http://xmlns.oracle.com/cloud/adapter/REST/Get_First_Role_REQUEST/types" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:nsmpr0="http://xmlns.oracle.com/cloud/adapter/REST/Get_Users_REQUEST" xmlns:nssrcdfl="http://xmlns.oracle.com/cloud/adapter/REST/Get-Users/types" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" ns2 oraext xsd xp20 nssrcmpr ora oracle-xsl-mapper xsi fn nsmpr0 nssrcdfl xsl ignore01" xmlns:ignore01="http://www.oracle.com/XSL/Transform/java" ignore01:ignorexmlids="true" xmlns:xml="http://www.w3.org/XML/1998/namespace" xmlns:nsmpr1="http://xml.oracle.com/types/REST/Get_First_Role_REQUEST" xmlns:nsmpr2="http://xml.oracle.com/types/REST/Get_Users_REQUEST">
	<oracle-xsl-mapper:schema xml:id="id_2">
		<!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
		<oracle-xsl-mapper:mapSources xml:id="id_3">
			<oracle-xsl-mapper:source type="WSDL" xml:id="id_4">
				<oracle-xsl-mapper:schema location="../../application_8/outbound_9/resourcegroup_10/Get_Users_REQUEST.wsdl" xml:id="id_5"/>
				<oracle-xsl-mapper:rootElement name="execute" namespace="http://xmlns.oracle.com/cloud/adapter/REST/Get_Users_REQUEST/types" xml:id="id_6"/>
			</oracle-xsl-mapper:source>
		</oracle-xsl-mapper:mapSources>
		<oracle-xsl-mapper:mapTargets xml:id="id_7">
			<oracle-xsl-mapper:target type="WSDL" xml:id="id_8">
				<oracle-xsl-mapper:schema location="../../application_24/inbound_25/resourcegroup_26/Get_First_Role_REQUEST.wsdl" xml:id="id_9"/>
				<oracle-xsl-mapper:rootElement name="execute" namespace="http://xmlns.oracle.com/cloud/adapter/REST/Get_First_Role_REQUEST/types" xml:id="id_10"/>
			</oracle-xsl-mapper:target>
		</oracle-xsl-mapper:mapTargets>
		<!--GENERATED BY ORACLE XSL MAPPER 12.1.2.0.0-->
	</oracle-xsl-mapper:schema>
	<!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
	<xsl:template match="/" xml:id="id_11">
		<nstrgmpr:execute xml:id="id_12">
			<nstrgmpr:TemplateParameters xml:id="id_16">
				<nsmpr1:role xml:id="id_17">
					<xsl:value-of select="/nssrcmpr:execute/nssrcmpr:TemplateParameters/nsmpr2:secondRole" xml:id="id_18"/>
				</nsmpr1:role>
			</nstrgmpr:TemplateParameters>
		</nstrgmpr:execute>
	</xsl:template>
</xsl:stylesheet>